spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://${MAIN_MYSQL_HOST}:${MAIN_DB_PORT:3306}/${MAIN_DB_NAME:stag_dms}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${MAIN_MYSQL_USERNAME}
    password: ${MAIN_MYSQL_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:1234}

  jpa:
    properties:
      hibernate:
        show_sql: ${MAIN_DEV_SHOW_SQL:false}
