spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://${MAIN_MYSQL_HOST:127.0.0.1}:${MAIN_DB_PORT:3311}/${MAIN_DB_NAME:main_prod_mysql}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${MAIN_MYSQL_USERNAME:root}
    password: ${MAIN_MYSQL_PASSWORD:}

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:asdf}
