spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://${NOTIFICATION_MYSQL_HOST:localhost}:${NOTIFICATION_DB_PORT:3313}/${NOTIFICATION_DB_NAME:notification_stag_mysql}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${NOTIFICATION_MYSQL_USERNAME:root}
    password: ${NOTIFICATION_MYSQL_PASSWORD:}

  rabbitmq:
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:localhost}